### ISSUE TITLE
Backend routes

### ISSUE THREAD

**Issue by linakherchi** [abelchiao/asana_clone#3]
- [x] Contains the following sections: HTML, API Endpoints(Backend)
- [x] Each route has a description
- [x] API Endpoint routes contains wildcard variables written in `snake_case`
- [x] Routes does not contain [superfluous routes](https://github.com/appacademy/curriculum/blob/master/rails/readings/routing-part-ii.md)
- [x] Have API routes that will allow the front end to get all info it needs and does not have unneeded routes:
    + probably doesn't need a `GET likes` api endpoint because that info comes through the post show

**Comment by linakherchi** [comment]
Thanks, Abel !
Member routes do not need to be nested

**Comment by abelchiao** [comment]
Should be fixed now!
