### ISSUE TITLE
PA Review: User Authentication

### ISSUE THREAD

**Issue by abelchiao** [abelchiao/asana_clone#7]
- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components and Containers
- [x] Styling
- [x] Smooth, bug-free navigation
- [x] Adequate and appropriate seeds

**Comment by linakherchi** [comment]
Great ! Everything looks great ! One thing to note is that your column names should become camelCased in the frontend. Thus, please add camelize in your environment.rb file. 
Feel free to start working on the next feature !

**Comment by abelchiao** [comment]
Added camelized - state keys are now cameCased!

**Comment by linakherchi** [comment]
Great !
